# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.proto import hardware_daemon_pb2 as hardware__daemon__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hardware_daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HardwareDaemonStub(object):
    """============================================================================
    HardwareDaemon — gRPC service contract

    This is the ONLY interface between the Test Worker Runtime (Python) and
    the Hardware Daemon (C++ production / Python mock).

    Design rules:
    - Worker never talks to hardware directly. All hardware access goes
    through this service.
    - Daemon is stateless from the Worker's perspective: each RPC is
    self-contained. The daemon manages connection state internally.
    - device_id identifies which physical device to target:
    "monitoring_pcb" — primary target, relays to Robot PCB over CAN
    "robot_pcb"      — direct UART, optional double-verification only
    - All timeouts specified by the caller (Worker), not hardcoded in daemon.
    The daemon is a pure execution engine.

    Extending for new hardware (e.g. PSU, oscilloscope):
    1. Use new device_id string — convention only, no enum, keeps proto
    stable without recompilation as devices are added.
    2. Add new RPC only if the interaction pattern is genuinely new.
    3. Implement handler in mock_daemon.py and later in real C++ daemon.
    4. Worker step_engine.py adds a handler for any new StepType.
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/hardware_daemon.HardwareDaemon/Ping',
                request_serializer=hardware__daemon__pb2.PingRequest.SerializeToString,
                response_deserializer=hardware__daemon__pb2.PingResponse.FromString,
                _registered_method=True)
        self.CheckDeviceReady = channel.unary_unary(
                '/hardware_daemon.HardwareDaemon/CheckDeviceReady',
                request_serializer=hardware__daemon__pb2.DeviceReadyRequest.SerializeToString,
                response_deserializer=hardware__daemon__pb2.DeviceReadyResponse.FromString,
                _registered_method=True)
        self.DiscoverCapabilities = channel.unary_unary(
                '/hardware_daemon.HardwareDaemon/DiscoverCapabilities',
                request_serializer=hardware__daemon__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=hardware__daemon__pb2.DiscoverResponse.FromString,
                _registered_method=True)
        self.SendCommand = channel.unary_unary(
                '/hardware_daemon.HardwareDaemon/SendCommand',
                request_serializer=hardware__daemon__pb2.CommandRequest.SerializeToString,
                response_deserializer=hardware__daemon__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.WaitForChannel = channel.unary_unary(
                '/hardware_daemon.HardwareDaemon/WaitForChannel',
                request_serializer=hardware__daemon__pb2.ChannelWaitRequest.SerializeToString,
                response_deserializer=hardware__daemon__pb2.ChannelWaitResponse.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.unary_stream(
                '/hardware_daemon.HardwareDaemon/StreamTelemetry',
                request_serializer=hardware__daemon__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=hardware__daemon__pb2.TelemetryFrame.FromString,
                _registered_method=True)
        self.RebootDevice = channel.unary_unary(
                '/hardware_daemon.HardwareDaemon/RebootDevice',
                request_serializer=hardware__daemon__pb2.RebootRequest.SerializeToString,
                response_deserializer=hardware__daemon__pb2.RebootResponse.FromString,
                _registered_method=True)
        self.ApplyBoardConfig = channel.unary_unary(
                '/hardware_daemon.HardwareDaemon/ApplyBoardConfig',
                request_serializer=hardware__daemon__pb2.BoardConfigRequest.SerializeToString,
                response_deserializer=hardware__daemon__pb2.BoardConfigResponse.FromString,
                _registered_method=True)


class HardwareDaemonServicer(object):
    """============================================================================
    HardwareDaemon — gRPC service contract

    This is the ONLY interface between the Test Worker Runtime (Python) and
    the Hardware Daemon (C++ production / Python mock).

    Design rules:
    - Worker never talks to hardware directly. All hardware access goes
    through this service.
    - Daemon is stateless from the Worker's perspective: each RPC is
    self-contained. The daemon manages connection state internally.
    - device_id identifies which physical device to target:
    "monitoring_pcb" — primary target, relays to Robot PCB over CAN
    "robot_pcb"      — direct UART, optional double-verification only
    - All timeouts specified by the caller (Worker), not hardcoded in daemon.
    The daemon is a pure execution engine.

    Extending for new hardware (e.g. PSU, oscilloscope):
    1. Use new device_id string — convention only, no enum, keeps proto
    stable without recompilation as devices are added.
    2. Add new RPC only if the interaction pattern is genuinely new.
    3. Implement handler in mock_daemon.py and later in real C++ daemon.
    4. Worker step_engine.py adds a handler for any new StepType.
    ============================================================================

    """

    def Ping(self, request, context):
        """-------------------------------------------------------------------------
        Lifecycle
        -------------------------------------------------------------------------

        Confirm daemon is alive and connected.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDeviceReady(self, request, context):
        """Check if a specific device is ready to receive commands.
        Called by Worker after board reboot, before executing TestCases.
        Returns board_identity: the string the board announced on UART after
        boot. Controller cross-checks this against expected_board_identity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverCapabilities(self, request, context):
        """-------------------------------------------------------------------------
        Discovery
        -------------------------------------------------------------------------

        Trigger the GScope UART discovery handshake with the Monitoring PCB.
        Returns all available channels and commands for this firmware build.
        Board must be ready (CheckDeviceReady passed) before calling this.
        Mock: returns hardcoded DiscoverResponse for the shuttle assembly.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """-------------------------------------------------------------------------
        Command execution  (maps to: StepType.CONSOLE)
        -------------------------------------------------------------------------

        Send a GScope command over UART, wait for response string.
        Daemon reads UART until return_string_match is found (PASS) or
        timeout_ms elapses (INFRA error). If return_string_match is empty,
        returns on first non-empty response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitForChannel(self, request, context):
        """-------------------------------------------------------------------------
        Channel monitoring  (maps to: StepType.CHANNEL_WAIT)
        -------------------------------------------------------------------------

        Monitor a GScope channel until value[channel_offset] is in
        [min_value, max_value], or timeout_ms elapses.
        Daemon runs the polling loop internally — Worker makes one blocking
        call. All UART timing stays inside the daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request, context):
        """Stream live channel telemetry (for Monitoring Service / dashboards).
        Not used by the Worker step engine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebootDevice(self, request, context):
        """-------------------------------------------------------------------------
        Board management  (called by Controller, NOT by Worker)
        -------------------------------------------------------------------------

        Issue a reboot command to the Robot PCB.
        Returns when command is issued — does NOT wait for readiness.
        Follow with CheckDeviceReady to confirm board is back up.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyBoardConfig(self, request, context):
        """Send DIP switch config byte to the ESP32 over UART, wait for ACK.
        Mock: always returns CONFIG_APPLIED immediately.
        Real: sends byte, waits for "CONFIG_APPLIED" response string.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HardwareDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=hardware__daemon__pb2.PingRequest.FromString,
                    response_serializer=hardware__daemon__pb2.PingResponse.SerializeToString,
            ),
            'CheckDeviceReady': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDeviceReady,
                    request_deserializer=hardware__daemon__pb2.DeviceReadyRequest.FromString,
                    response_serializer=hardware__daemon__pb2.DeviceReadyResponse.SerializeToString,
            ),
            'DiscoverCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverCapabilities,
                    request_deserializer=hardware__daemon__pb2.DiscoverRequest.FromString,
                    response_serializer=hardware__daemon__pb2.DiscoverResponse.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=hardware__daemon__pb2.CommandRequest.FromString,
                    response_serializer=hardware__daemon__pb2.CommandResponse.SerializeToString,
            ),
            'WaitForChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitForChannel,
                    request_deserializer=hardware__daemon__pb2.ChannelWaitRequest.FromString,
                    response_serializer=hardware__daemon__pb2.ChannelWaitResponse.SerializeToString,
            ),
            'StreamTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=hardware__daemon__pb2.TelemetryRequest.FromString,
                    response_serializer=hardware__daemon__pb2.TelemetryFrame.SerializeToString,
            ),
            'RebootDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RebootDevice,
                    request_deserializer=hardware__daemon__pb2.RebootRequest.FromString,
                    response_serializer=hardware__daemon__pb2.RebootResponse.SerializeToString,
            ),
            'ApplyBoardConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyBoardConfig,
                    request_deserializer=hardware__daemon__pb2.BoardConfigRequest.FromString,
                    response_serializer=hardware__daemon__pb2.BoardConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hardware_daemon.HardwareDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hardware_daemon.HardwareDaemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HardwareDaemon(object):
    """============================================================================
    HardwareDaemon — gRPC service contract

    This is the ONLY interface between the Test Worker Runtime (Python) and
    the Hardware Daemon (C++ production / Python mock).

    Design rules:
    - Worker never talks to hardware directly. All hardware access goes
    through this service.
    - Daemon is stateless from the Worker's perspective: each RPC is
    self-contained. The daemon manages connection state internally.
    - device_id identifies which physical device to target:
    "monitoring_pcb" — primary target, relays to Robot PCB over CAN
    "robot_pcb"      — direct UART, optional double-verification only
    - All timeouts specified by the caller (Worker), not hardcoded in daemon.
    The daemon is a pure execution engine.

    Extending for new hardware (e.g. PSU, oscilloscope):
    1. Use new device_id string — convention only, no enum, keeps proto
    stable without recompilation as devices are added.
    2. Add new RPC only if the interaction pattern is genuinely new.
    3. Implement handler in mock_daemon.py and later in real C++ daemon.
    4. Worker step_engine.py adds a handler for any new StepType.
    ============================================================================

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hardware_daemon.HardwareDaemon/Ping',
            hardware__daemon__pb2.PingRequest.SerializeToString,
            hardware__daemon__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckDeviceReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hardware_daemon.HardwareDaemon/CheckDeviceReady',
            hardware__daemon__pb2.DeviceReadyRequest.SerializeToString,
            hardware__daemon__pb2.DeviceReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hardware_daemon.HardwareDaemon/DiscoverCapabilities',
            hardware__daemon__pb2.DiscoverRequest.SerializeToString,
            hardware__daemon__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hardware_daemon.HardwareDaemon/SendCommand',
            hardware__daemon__pb2.CommandRequest.SerializeToString,
            hardware__daemon__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitForChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hardware_daemon.HardwareDaemon/WaitForChannel',
            hardware__daemon__pb2.ChannelWaitRequest.SerializeToString,
            hardware__daemon__pb2.ChannelWaitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hardware_daemon.HardwareDaemon/StreamTelemetry',
            hardware__daemon__pb2.TelemetryRequest.SerializeToString,
            hardware__daemon__pb2.TelemetryFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebootDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hardware_daemon.HardwareDaemon/RebootDevice',
            hardware__daemon__pb2.RebootRequest.SerializeToString,
            hardware__daemon__pb2.RebootResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyBoardConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hardware_daemon.HardwareDaemon/ApplyBoardConfig',
            hardware__daemon__pb2.BoardConfigRequest.SerializeToString,
            hardware__daemon__pb2.BoardConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
